version: "3"
 
services:
  web_client:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
  flask_app:
    build: 
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
        - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=whorunthehelloworld
      - POSTGRES_DB=mayaridb
    ports:
      - 5432:5432
volumes:
  postgres_data: