version: "3"
 
services:
  web_client:
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
  flask_app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend