FROM python:3.8-slim-buster

WORKDIR /backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat


COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . /backend/

ENV FLASK_APP=server.py

RUN pip3 install gunicorn[gevent]

#CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

EXPOSE 5000
# run entrypoint.sh
ENTRYPOINT ["/backend/entrypoint.sh"]