"""empty message

Revision ID: 5233aeceab32
Revises: c5f12b60c547
Create Date: 2022-03-29 05:06:39.434689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233aeceab32'
down_revision = 'c5f12b60c547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('installments', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'installments')
    # ### end Alembic commands ###
