"""empty message

Revision ID: bbbe9a128319
Revises: 7f7be73bbd4f
Create Date: 2022-04-12 03:08:44.643772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbe9a128319'
down_revision = '7f7be73bbd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
